version: "3.8"

services:
  backend:
    build: ./backend
    volumes:
      - stock_data:/app/data  # Shared JSON file
    restart: always

  api:
    build: ./api
    ports:
      - "5000:5000"
    depends_on:
      - backend
    volumes:
      - stock_data:/app/data  # Shared JSON file
    restart: always

volumes:
  stock_data:
